modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Sweenus/SimplySwords/issues"
license = "Timefall Development License"

[[mods]]
modId = "simplyswordsiceandfire"
version = "1.54.0-1.20.1"
displayName = "Simply Swords - Ice and Fire"
authors = "Bull"
credits="E"
description = '''
A variety of unique weapons to add to your minecraft repertoire
'''
logoFile = ""

[[dependencies.simplyswordsiceandfire]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswordsiceandfire]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswordsiceandfire]]
modId = "architectury"
mandatory = true
versionRange = "[5.12.42,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplyswordsiceandfire]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.106,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplyswordsiceandfire]]
modId = "simplyswords"
mandatory = true
versionRange = "[1.54.0-1.20.1,)"
ordering = "NONE"
side = "BOTH"